import type { AgentMeta } from '../types'

/**
 * Plantilla profesional Foro Inversor — ≥30 especialistas + CIO.
 * Cada agente: nombre ES, rol, descripción y nota de metodología.
 */
export const AGENT_ROSTER: AgentMeta[] = [
  {
    id: 'cio-mesa',
    name: 'Presidente / CIO de mesa',
    shortName: 'CIO',
    role: 'Moderación IC y estrategias',
    description: 'Modera mesa institucional y valida coherencia de la estrategia a medida.',
    methodology: 'Síntesis jerárquica: disenso explícito, bandas de recomendación, condiciones de revisión.',
    color: '#e2e8f0',
    icon: '🪑',
    isChair: true,
    defaultSelected: true,
  },
  {
    id: 'renta-variable',
    name: 'Analista de renta variable',
    shortName: 'RV',
    role: 'Fundamentos y moat',
    description: 'Calidad del negocio, ventajas competitivas, crecimiento y valoración fundamental.',
    methodology: 'Checklist de moat, unit economics, ROIC y sostenibilidad de márgenes.',
    color: '#3b82f6',
    icon: '📈',
    defaultSelected: true,
  },
  {
    id: 'tecnico',
    name: 'Analista técnico',
    shortName: 'AT',
    role: 'Precio y timing',
    description: 'Estructura de precios, tendencias, soportes/resistencias y momentum (educativo).',
    methodology: 'Tendencia multi-timeframe, volatilidad y zonas de riesgo táctico — no predicción mágica.',
    color: '#8b5cf6',
    icon: '📉',
    defaultSelected: true,
  },
  {
    id: 'etfs-fondos',
    name: 'Especialista en ETFs y fondos',
    shortName: 'ETF',
    role: 'Vehículos indexados',
    description: 'TER, tracking, réplica, domicilio UCITS y adecuación al objetivo.',
    methodology: 'Comparativa de costes, política Acc/Dist, tamaño AUM y liquidez del vehículo.',
    color: '#06b6d4',
    icon: '🗂️',
    defaultSelected: true,
  },
  {
    id: 'macro',
    name: 'Analista macro',
    shortName: 'MAC',
    role: 'Ciclo y política',
    description: 'Tipos, inflación, crecimiento, divisas y régimen de mercado.',
    methodology: 'Mapa de regímenes (crecimiento/inflación) y sensibilidad de carteras.',
    color: '#f59e0b',
    icon: '🌍',
    defaultSelected: true,
  },
  {
    id: 'riesgo-cartera',
    name: 'Agente de riesgo y cartera',
    shortName: 'RSK',
    role: 'Riesgo agregado',
    description: 'Concentración, correlaciones, drawdown potencial y encaje en cartera.',
    methodology: 'Límites de peso, overlap factor y estrés de escenarios educativos.',
    color: '#ef4444',
    icon: '🛡️',
    defaultSelected: true,
  },
  {
    id: 'abogado-diablo',
    name: 'Abogado del diablo',
    shortName: 'ADV',
    role: 'Red team',
    description: 'Cuestiona la tesis, busca sesgos y escenarios adversos.',
    methodology: 'Preguntas de falsación, sesgo de confirmación y riesgos de cola.',
    color: '#f97316',
    icon: '😈',
    defaultSelected: true,
  },
  {
    id: 'cumplimiento',
    name: 'Custodio de cumplimiento / avisos',
    shortName: 'CMP',
    role: 'Avisos legales',
    description: 'Disclaimers, hechos vs juicios y límites educativos del producto.',
    methodology: 'Plantillas de aviso, etiquetado demo y separación consejo vs educación.',
    color: '#64748b',
    icon: '⚖️',
    defaultSelected: true,
  },
  {
    id: 'dividendos',
    name: 'Estratega de dividendos e ingresos',
    shortName: 'DIV',
    role: 'Renta e ingresos',
    description: 'Sostenibilidad del dividendo, payout, yield y retorno al accionista.',
    methodology: 'Cobertura FCF/payout y calidad de la política de retribución.',
    color: '#22c55e',
    icon: '💰',
    defaultSelected: false,
  },
  {
    id: 'valoracion-cuant',
    name: 'Analista de valoración cuantitativa',
    shortName: 'VAL',
    role: 'Múltiplos y modelos',
    description: 'P/E, EV/EBITDA, FCF yield y rangos relativos (demo).',
    methodology: 'Comparables, percentiles históricos y sensibilidad a crecimiento.',
    color: '#14b8a6',
    icon: '🔢',
    defaultSelected: true,
  },
  {
    id: 'smallcaps-growth',
    name: 'Especialista en small caps y growth',
    shortName: 'SMG',
    role: 'Crecimiento',
    description: 'TAM, unit economics, ejecución y asimetría en growth/small caps.',
    methodology: 'Calidad de crecimiento vs. precio; liquidez mínima para el tamaño de cuenta.',
    color: '#a855f7',
    icon: '🚀',
    defaultSelected: false,
  },
  {
    id: 'esg',
    name: 'Analista ESG / sostenibilidad',
    shortName: 'ESG',
    role: 'Factores ESG',
    description: 'Riesgos E, S y G de forma educativa (no certificación).',
    methodology: 'Exclusiones, controversias materiales y encaje con mandato ESG del usuario.',
    color: '#84cc16',
    icon: '🌿',
    defaultSelected: false,
  },
  {
    id: 'renta-fija',
    name: 'Especialista en renta fija y duration',
    shortName: 'RF',
    role: 'Tipos y bonos',
    description: 'Duration, crédito y rol de RF en fondos/ETFs mixtos.',
    methodology: 'Curva, spread de crédito y matching aproximado a horizonte.',
    color: '#0ea5e9',
    icon: '🏦',
    defaultSelected: true,
  },
  {
    id: 'liquidez',
    name: 'Analista de liquidez y microstructure',
    shortName: 'LIQ',
    role: 'Liquidez',
    description: 'Spreads, volumen, impacto de mercado y ejecución.',
    methodology: 'Filtro de negociabilidad según capital y ticket medio.',
    color: '#eab308',
    icon: '💧',
    defaultSelected: true,
  },
  {
    id: 'fiscal',
    name: 'Especialista fiscal para inversores',
    shortName: 'FIS',
    role: 'Notas fiscales ES',
    description: 'Notas educativas IRPF/fondos/ETF orientadas a España. No es asesoría fiscal.',
    methodology: 'Diferir vs realizar, Acc/Dist, y recordatorio de consulta profesional.',
    color: '#78716c',
    icon: '🧾',
    defaultSelected: true,
  },
  {
    id: 'scouting',
    name: 'Scouting de oportunidades / catalysts',
    shortName: 'SCO',
    role: 'Catalizadores',
    description: 'Eventos, catalizadores y ventanas de atención del mercado.',
    methodology: 'Calendario de revisión, no trading especulativo.',
    color: '#ec4899',
    icon: '🔭',
    defaultSelected: false,
  },
  {
    id: 'sector-tech',
    name: 'Especialista sector tecnología',
    shortName: 'TEC',
    role: 'Sector tech',
    description: 'Software, semis, plataformas y ciclos de capex tecnológico.',
    methodology: 'Mapa subsectorial, concentración FAANG/ Mag7 y riesgos regulatorios.',
    color: '#38bdf8',
    icon: '💻',
    defaultSelected: false,
  },
  {
    id: 'sector-salud',
    name: 'Especialista sector salud',
    shortName: 'HLT',
    role: 'Healthcare',
    description: 'Farma, biotecnología, dispositivos y pagos sanitarios.',
    methodology: 'Pipeline, reembolso y riesgo binario en biotech vs. calidad defensiva.',
    color: '#f43f5e',
    icon: '🩺',
    defaultSelected: false,
  },
  {
    id: 'sector-energia',
    name: 'Especialista sector energía',
    shortName: 'ENE',
    role: 'Energía',
    description: 'Oil & gas, utilities y transición energética.',
    methodology: 'Ciclo de commodities, regulación y sensibilidad a tipos en utilities.',
    color: '#facc15',
    icon: '⚡',
    defaultSelected: false,
  },
  {
    id: 'sector-financieros',
    name: 'Especialista sector financieros',
    shortName: 'FIN',
    role: 'Banks & finance',
    description: 'Bancos, seguros y gestores de activos.',
    methodology: 'NIM, calidad crediticia, capital regulatorio y ciclo.',
    color: '#6366f1',
    icon: '🏛️',
    defaultSelected: false,
  },
  {
    id: 'sector-consumo',
    name: 'Especialista sector consumo',
    shortName: 'CON',
    role: 'Consumer',
    description: 'Consumo discrecional vs. básico; marcas y elasticidad.',
    methodology: 'Pricing power, inventarios y sensibilidad a renta disponible.',
    color: '#fb7185',
    icon: '🛒',
    defaultSelected: false,
  },
  {
    id: 'alternativos-reits',
    name: 'Especialista en alternativos y REITs',
    shortName: 'ALT',
    role: 'Alternativos / inmobiliario',
    description: 'Visión educativa de REITs, infra y materias primas vía ETFs.',
    methodology: 'Rol diversificador, liquidez del vehículo y costes; evitar productos opacos.',
    color: '#d946ef',
    icon: '🏢',
    defaultSelected: false,
  },
  {
    id: 'behavioral',
    name: 'Especialista en finanzas conductuales',
    shortName: 'BEH',
    role: 'Sesgos y disciplina',
    description: 'Sesgos (pérdida, FOMO, home bias) y diseño de reglas de aportación.',
    methodology: 'Pre-compromisos, DCA y checklist anti-pánico en drawdowns.',
    color: '#c084fc',
    icon: '🧠',
    defaultSelected: true,
  },
  {
    id: 'taxlots',
    name: 'Conciencia de lotes fiscales (educativo)',
    shortName: 'LOT',
    role: 'Tax lots / realización',
    description: 'Conciencia educativa sobre realización de plusvalías y orden de venta (ES).',
    methodology: 'Notas generales FIFO/selección; no sustituye software ni asesor fiscal.',
    color: '#a8a29e',
    icon: '📑',
    defaultSelected: false,
  },
  {
    id: 'fx-multicurrency',
    name: 'Analista FX y multi-divisa',
    shortName: 'FX',
    role: 'Divisas',
    description: 'Exposición EUR/USD/otras y cobertura aproximada vía vehículos.',
    methodology: 'Identificar divisa económica vs. cotización; coste de hedge.',
    color: '#2dd4bf',
    icon: '💱',
    defaultSelected: true,
  },
  {
    id: 'inflacion',
    name: 'Estratega de cobertura de inflación',
    shortName: 'INF',
    role: 'Inflación',
    description: 'Activos y sleeves con sensibilidad a inflación (educativo).',
    methodology: 'Linker/breakevens vía ETF, REITs, commodities — con límites claros.',
    color: '#fb923c',
    icon: '🔥',
    defaultSelected: false,
  },
  {
    id: 'jubilacion',
    name: 'Planificador de horizonte / jubilación',
    shortName: 'HOR',
    role: 'Horizonte temporal',
    description: 'Encaje de asignación a horizonte, glideslope educativo y secuencia de retiros.',
    methodology: 'Buckets por plazo; no es plan de pensiones personalizado regulado.',
    color: '#60a5fa',
    icon: '⏳',
    defaultSelected: true,
  },
  {
    id: 'asignacion',
    name: 'Arquitecto de asignación de activos',
    shortName: 'AA',
    role: 'Asset allocation',
    description: 'Diseña mix RV/RF/líquido/alternativos según capital, riesgo y metas.',
    methodology: 'Bandas estratégicas + restricciones de producto por tamaño de cuenta.',
    color: '#4ade80',
    icon: '🧩',
    defaultSelected: true,
  },
  {
    id: 'productos-retail-es',
    name: 'Especialista productos retail España',
    shortName: 'ES',
    role: 'Universo ES / UCITS',
    description: 'Preferencia por UCITS negociables en Europa y operativa típica retail ES.',
    methodology: 'Filtro de domicilio, KIID/folleto y accesibilidad en brókers comunes (demo).',
    color: '#f472b6',
    icon: '🇪🇸',
    defaultSelected: true,
  },
  {
    id: 'calidad-factor',
    name: 'Analista factores / quality-value',
    shortName: 'FAC',
    role: 'Smart beta / factores',
    description: 'Tilts quality, value, momentum vía ETFs factoriales (educativo).',
    methodology: 'Coste del tilt, crowding y encaje con núcleo market-cap.',
    color: '#818cf8',
    icon: '📊',
    defaultSelected: false,
  },
  {
    id: 'credito',
    name: 'Analista de crédito corporativo',
    shortName: 'CRD',
    role: 'Credit spreads',
    description: 'IG vs HY, spreads y rol del crédito en el sleeve de RF.',
    methodology: 'Compensación spread vs. default; evitar HY excesivo en perfiles conservadores.',
    color: '#34d399',
    icon: '📋',
    defaultSelected: false,
  },
  {
    id: 'emergentes',
    name: 'Especialista mercados emergentes',
    shortName: 'EM',
    role: 'Emerging markets',
    description: 'Exposición EM vía ETF: oportunidades, gobernanza y divisa.',
    methodology: 'Peso satélite, China risk y liquidez del vehículo.',
    color: '#fbbf24',
    icon: '🌏',
    defaultSelected: false,
  },
]

export function getAgent(id: string): AgentMeta | undefined {
  return AGENT_ROSTER.find((a) => a.id === id)
}

export const SPECIALIST_IDS = AGENT_ROSTER.filter((a) => !a.isChair).map((a) => a.id)

export function assertRosterSize(min = 30) {
  if (AGENT_ROSTER.length < min) {
    throw new Error(`Roster insuficiente: ${AGENT_ROSTER.length} < ${min}`)
  }
}
